@ECHO OFF

IF NOT EXIST "%~dp0ENHANCD.BAT" (
	ECHO ENHANCD.BAT does not exist.1>&2
	EXIT /B 1
)

IF NOT DEFINED ENHANCD_FZY (
	ECHO Environment variable ENHANCD_FZY must be set the path to fzy.exe.
	EXIT /B 1
)

IF NOT DEFINED ENHANCD_DIR (
	SET ENHANCD_DIR=%LOCALAPPDATA%\enhancd
)

IF NOT DEFINED ENHANCD_LOG (
	SET ENHANCD_LOG=%ENHANCD_DIR%\enhancd.log
)

IF NOT DEFINED ENHANCD_HYPHEN_NUM SET ENHANCD_HYPHEN_NUM=10

IF NOT EXIST "%ENHANCD_DIR%" MKDIR "%ENHANCD_DIR%"
IF NOT EXIST "%ENHANCD_LOG%" TYPE NUL > "%ENHANCD_LOG%"

DOSKEY CD="%~dp0ENHANCD.BAT" $*

