@ECHO OFF

IF NOT EXIST "%~dp0ENHANCD.BAT" (
	ECHO ENHANCD.BAT does not exist.1>&2
	EXIT /B 1
)

IF NOT DEFINED ENHANCD_FZY (
	FOR /F "delims=" %%I IN ('WHERE fzy.exe 2^>NUL') DO SET "ENHANCD_FZY=%%I"
)

IF NOT DEFINED ENHANCD_FZY (
	ECHO ENHANCD.BAT requires fzy.exe. Please put it under PATH or set environment variable ENHANCD_FZY to its path.1>&2
	EXIT /B 1
)

IF NOT DEFINED ENHANCD_DIR SET "ENHANCD_DIR=%LOCALAPPDATA%\enhancd"
IF NOT DEFINED ENHANCD_LOG SET "ENHANCD_LOG=%ENHANCD_DIR%\enhancd.log"
IF NOT DEFINED ENHANCD_TMP SET "ENHANCD_TMP=%ENHANCD_DIR%\enhancd.tmp"
IF NOT DEFINED ENHANCD_HYPHEN_NUM SET ENHANCD_HYPHEN_NUM=10

IF NOT EXIST "%ENHANCD_DIR%" MKDIR "%ENHANCD_DIR%"
IF NOT EXIST "%ENHANCD_LOG%" TYPE NUL > "%ENHANCD_LOG%"

DOSKEY CD="%~dp0ENHANCD.BAT" $*

